### ISSUE TITLE
missing and broken labels

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshSmartInputLabel#1]
### PHP Version

-

### Shopware Version

-

### Actual behaviour

Missing labels in cart:
- promotion code
- add product by number

Ugly label in contact form for salutation:
![image](https://user-images.githubusercontent.com/135993/137626696-a0df25e8-55ac-4e50-a860-0028fe3e7773.png)

### Expected behaviour

have labels shown

### Steps to Reproduce?

Open shop and see the named sources.

**Comment by pumpi** [comment]
The hidden labels are Screen Reader only labels. Did you think we must Change the Screen reader only  labels to normal labels?

Did you see the ugly placeholder in the ajax contact form?

**Comment by tinect** [comment]
> The hidden labels are Screen Reader only labels. Did you think we must Change the Screen reader only labels to normal labels?

Oh yes. Otherwise the customer cannot see what the fields are for.
> Did you see the ugly placeholder in the ajax contact form?

Yes

**Comment by pumpi** [comment]
> Oh yes. Otherwise the customer cannot see what the fields are for.

Yes we could also use the actual placeholder function that is why I ask

**Comment by pumpi** [comment]
fixed by #3 and 29d97aa469c9ae585bbf3aab9c5ea8bf0e6c924b
